# Generated by Django 5.2.7 on 2025-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Expense", "0005_alter_category_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
